[project]
name = "cli-todolist"
version = "0.1.0"
description = "A Simple Command-Line Todo List Manager"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
    "sqlalchemy>=2.0.36",
]
